### ISSUE TITLE
Random test error on test_partitioning

### ISSUE THREAD

**Issue by nippoo** [klusta-team/klustakwik2#48]
This only happens _some_ of the time.

```
======================================================================
ERROR: klustakwik2.tests.test_partitioning.test_partitioning
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/testenv/lib/python3.3/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/kwikteam/klustakwik2/klustakwik2/tests/test_partitioning.py", line 12, in test_partitioning
    data = generate_multimask_test_data(10, 10, 5)
  File "/home/travis/build/kwikteam/klustakwik2/klustakwik2/tests/test_mask_starts.py", line 43, in generate_multimask_test_data
    fet, fmask, unmasked, offsets).to_sparse_data()
  File "/home/travis/build/kwikteam/klustakwik2/klustakwik2/data.py", line 69, in to_sparse_data
    float_num_unmasked = compute_float_num_unmasked(self)
  File "/home/travis/build/kwikteam/klustakwik2/klustakwik2/precomputations.py", line 56, in compute_float_num_unmasked
    return add.reduceat(data.masks, data.offsets[:-1])
IndexError: index 19 out-of-bounds in add.reduceat [0, 19)
```

**Comment by thesamovar** [comment]
Oh I never encountered that. Looks like a genuine bug.

**Comment by nippoo** [comment]
I've only got it once (out of about 20 test runs)

**Comment by nippoo** [comment]
OK, running it a few thousand times shows it happens about 2.5% of the time (always `index n out-of-bounds in add.reduceat [0, n]`)

**Comment by thesamovar** [comment]
This should be fixed now: @nippoo can you verify? (It works on mine.)
