### ISSUE TITLE
problem running on UCL's Legion server

### ISSUE THREAD

**Issue by nsteinme** [klusta-team/klustakwik2#62]
Got this error:

```
Traceback (most recent call last):
  File "/home/skgtnst/miniconda/envs/phy/bin/kk2_legacy", line 9, in <module>
    load_entry_point('klustakwik2==0.2.1', 'console_scripts', 'kk2_legacy')()
  File "/home/skgtnst/miniconda/envs/phy/lib/python3.4/site-packages/setuptools-17.1.1-py3.4.egg/pkg_resources/__init__.py", line 558, in load_entry_point
  File "/home/skgtnst/miniconda/envs/phy/lib/python3.4/site-packages/setuptools-17.1.1-py3.4.egg/pkg_resources/__init__.py", line 2682, in load_entry_point
  File "/home/skgtnst/miniconda/envs/phy/lib/python3.4/site-packages/setuptools-17.1.1-py3.4.egg/pkg_resources/__init__.py", line 2355, in load
  File "/home/skgtnst/miniconda/envs/phy/lib/python3.4/site-packages/setuptools-17.1.1-py3.4.egg/pkg_resources/__init__.py", line 2361, in resolve
  File "/home/skgtnst/miniconda/envs/phy/lib/python3.4/site-packages/klustakwik2/__init__.py", line 3, in <module>
    from .mask_starts import *
  File "/home/skgtnst/miniconda/envs/phy/lib/python3.4/site-packages/klustakwik2/mask_starts.py", line 5, in <module>
    from .numerics import mask_start_clusters
  File "/home/skgtnst/miniconda/envs/phy/lib/python3.4/site-packages/klustakwik2/numerics/__init__.py", line 7, in <module>
    from .cylib import *
  File "/home/skgtnst/miniconda/envs/phy/lib/python3.4/site-packages/klustakwik2/numerics/cylib/__init__.py", line 3, in <module>
    from .compute_cluster_masks import *
  File "/home/skgtnst/miniconda/envs/phy/lib/python3.4/site-packages/klustakwik2/numerics/cylib/compute_cluster_masks.py", line 1, in <module>
    from .compute_cluster_masks_cy import doaccum
ImportError: /home/skgtnst/miniconda/envs/phy/lib/python3.4/site-packages/klustakwik2/numerics/cylib/compute_cluster_masks_cy.cpython-34m.so: undefined symbol: _intel_fast_memcpy
```

**Comment by rossant** [comment]
- do you know the architecture of the node? just linux 64-bit?
- we could try to build a conda package for linux 64-bit and install it on legion via binstar -- cc @nippoo

**Comment by thesamovar** [comment]
Oh I somehow didn't notice this problem. I guess this is a cython issue not a specific kk issue?
